# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build-and-test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install poetry
      run: python -m pip install poetry
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"
        cache: "poetry"
    - name: Install dependencies
      run: |
        # python -m pip install poetry
        poetry install --with dev
    - name: Test with pytest
      env:
        BOTCH_API_TOKEN: ${{ secrets.BOTCH_API_TOKEN }}
      run: |
        poetry run pytest --cov=com --cov-report=xml --cov-report=html
    - name: Lint with Ruff
      run: |
        pip install ruff
        ruff check --output-format=github .
